//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTestClientEx.Main.Tools.TestClient.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Main.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WcfTestClientEx.Main.Tools.TestClient.UI.XmlPage", typeof(XmlPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool requestLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("requestLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=10}.
        /// </summary>
        internal static System.Drawing.Point requestLabel_Location {
            get {
                object obj = ResourceManager.GetObject("requestLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=47, Height=13}.
        /// </summary>
        internal static System.Drawing.Size requestLabel_Size {
            get {
                object obj = ResourceManager.GetObject("requestLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int requestLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("requestLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string requestLabel_Text {
            get {
                return ResourceManager.GetString("requestLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        internal static System.Windows.Forms.DockStyle requestPanel_Dock {
            get {
                object obj = ResourceManager.GetObject("requestPanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point requestPanel_Location {
            get {
                object obj = ResourceManager.GetObject("requestPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=629, Height=30}.
        /// </summary>
        internal static System.Drawing.Size requestPanel_Size {
            get {
                object obj = ResourceManager.GetObject("requestPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int requestPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("requestPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle requestXmlTextBox_Dock {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=30}.
        /// </summary>
        internal static System.Drawing.Point requestXmlTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool requestXmlTextBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ScrollBars similar to Both.
        /// </summary>
        internal static System.Windows.Forms.ScrollBars requestXmlTextBox_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.ScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=629, Height=90}.
        /// </summary>
        internal static System.Drawing.Size requestXmlTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int requestXmlTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool requestXmlTextBox_WordWrap {
            get {
                object obj = ResourceManager.GetObject("requestXmlTextBox.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool responseLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("responseLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=10}.
        /// </summary>
        internal static System.Drawing.Point responseLabel_Location {
            get {
                object obj = ResourceManager.GetObject("responseLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=13}.
        /// </summary>
        internal static System.Drawing.Size responseLabel_Size {
            get {
                object obj = ResourceManager.GetObject("responseLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int responseLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("responseLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string responseLabel_Text {
            get {
                return ResourceManager.GetString("responseLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        internal static System.Windows.Forms.DockStyle responsePanel_Dock {
            get {
                object obj = ResourceManager.GetObject("responsePanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point responsePanel_Location {
            get {
                object obj = ResourceManager.GetObject("responsePanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=629, Height=31}.
        /// </summary>
        internal static System.Drawing.Size responsePanel_Size {
            get {
                object obj = ResourceManager.GetObject("responsePanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int responsePanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("responsePanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle responseXmlTextBox_Dock {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=31}.
        /// </summary>
        internal static System.Drawing.Point responseXmlTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool responseXmlTextBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ScrollBars similar to Both.
        /// </summary>
        internal static System.Windows.Forms.ScrollBars responseXmlTextBox_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.ScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=629, Height=104}.
        /// </summary>
        internal static System.Drawing.Size responseXmlTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int responseXmlTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool responseXmlTextBox_WordWrap {
            get {
                object obj = ResourceManager.GetObject("responseXmlTextBox.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle xmlSplitContainer_Dock {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point xmlSplitContainer_Location {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Orientation similar to Horizontal.
        /// </summary>
        internal static System.Windows.Forms.Orientation xmlSplitContainer_Orientation {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.Orientation", resourceCulture);
                return ((System.Windows.Forms.Orientation)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=629, Height=259}.
        /// </summary>
        internal static System.Drawing.Size xmlSplitContainer_Size {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 123.
        /// </summary>
        internal static int xmlSplitContainer_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int xmlSplitContainer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("xmlSplitContainer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
